---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Execute script
      ansible.builtin.win_shell: |
        secedit /configure /quiet /db "c:\scripts\plantilla_windows.sdb" /cfg "c:\scripts\CCN-STIC-599B19 ENS categoria basica\CCN-STIC-599B19 ENS clientes independientes categoria basica.inf" /overwrite /log "c:\scripts\CCN-STIC-599B19 ENS categoria basica\plantilla_windows.log"