---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Execute script to configure services in the system
      ansible.builtin.win_shell: |
        secedit /configure /quiet /db "c:\scripts\servicios_windows.sdb" /cfg "c:\scripts\CCN-STIC-599B19 ENS categoria basica\CCN-STIC-599B19 ENS Servicios categoria basica.inf" /overwrite /log "c:\scripts\CCN-STIC-599B19 ENS categoria basica\servicios_windows.log"