---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Remove Scripts folder once all have been used
      ansible.builtin.win_file:
        path: C:\Scripts
        state: absent